# Generated by Django 4.2.11 on 2024-03-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RTSPUrl',
        ),
        migrations.AddField(
            model_name='camera',
            name='rtsp_url',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
