# Generated by Django 5.0.1 on 2024-02-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_camera_password_camera_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='ip_domain_name',
            new_name='ip_address',
        ),
    ]
