# Generated by Django 5.0.1 on 2024-02-28 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.camera')),
            ],
        ),
    ]
