# Generated by Django 4.2.11 on 2024-04-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_camera_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
