# Generated by Django 5.0.1 on 2024-02-18 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_ip_domain_name_camera_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTSPStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtsp_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='camera',
            name='password',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='rtsp_url',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='username',
        ),
        migrations.CreateModel(
            name='RTSPStreamCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('rtsp_stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.rtspstream')),
            ],
        ),
    ]
