# Generated by Django 4.2.11 on 2024-04-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_camera_serial_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='device_model',
            new_name='model',
        ),
    ]
