# Generated by Django 5.0.1 on 2024-02-29 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_testview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestView',
            new_name='TestModel',
        ),
    ]
