# Generated by Django 5.0.1 on 2024-02-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rtspstream_remove_camera_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTZCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('port', models.IntegerField(default=80)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.RemoveField(
            model_name='rtspstreamcredentials',
            name='rtsp_stream',
        ),
        migrations.DeleteModel(
            name='RTSPStream',
        ),
        migrations.DeleteModel(
            name='RTSPStreamCredentials',
        ),
    ]
