# Generated by Django 5.0.1 on 2024-02-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_testview_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='firmware_version',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='model',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
