# Generated by Django 5.0.1 on 2024-02-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_ptzcamera_delete_camera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTZControlHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pan', models.FloatField()),
                ('tilt', models.FloatField()),
                ('zoom', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='PTZCamera',
        ),
    ]
