# Generated by Django 5.0.1 on 2024-02-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_ptzcontrolhistory_delete_ptzcamera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=100)),
                ('certificate_base64', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='PTZControlHistory',
        ),
    ]
