# Generated by Django 5.0.1 on 2024-02-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_camera_firmware_version_camera_model_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
