# Generated by Django 5.0.1 on 2024-02-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_device_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
