# Generated by Django 5.0.1 on 2024-02-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_camera_certificate_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='camera_name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='channel_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='device_model',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='device_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='operation',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='ip',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='camera',
            name='port',
            field=models.IntegerField(default=80),
        ),
    ]
